name: GitHub Action Release Notes Preview
description: GitHub Action that publishes a new release.
inputs:
  github-token:
    required: true
    description: GitHub token that can checkout the repository as well as create tags/releases against it. e.g. 'secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
  extra-plugins:
    required: false
    description: Extra plugins for pre-install. You can also specify specifying version range for the extra plugins if you prefer.  Defaults to install @open-turo/semantic-release-config.
    default: |
      @open-turo/semantic-release-config@^1.4.0
  semantic-version:
    required: false
    description: Specify what version of semantic release to use
  template-url:
    required: false
    description: Breaking changes document template URL
    default: https://raw.githubusercontent.com/open-turo/actions-release/main/templates/breaking-changes.md
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
    - name: Install dependencies
      shell: bash
      run: npm install '@open-turo/semantic-release-config@^1.4.0'
    - uses: jwalton/gh-find-current-pr@v1
      id: find-pull-request
      with:
        state: open
    - name: Dry-run semantic-release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        ci: false
        dry_run: true
        debug: true
        extra_plugins: ${{ inputs.extra-plugins }}
        semantic_version: ${{ inputs.semantic-version }}
    - name: Validate breaking change doc exists
      uses: open-turo/actions-release/release-validate-breaking-doc-exists@f/add_breaking_changes_workflow
      with:
        last-release-version: ${{ steps.semantic.outputs.last_release_version }}
        new-release-version: ${{ steps.semantic.outputs.new_release_version }}
        pull-request-id: ${{ steps.find-pull-request.outputs.number }}
        github-token: ${{ inputs.github-token }}
