name: Release

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          semantic-release-extra-plugins: |
            @open-turo/semantic-release-config@4.0.3
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/test@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs:
      - lint
      - test
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-plugins: |
            @open-turo/semantic-release-config@4.0.3
