name: Update dependencies
concurrency: update-dependencies

on:
  schedule:
    # Every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
  issue_comment:
    types:
      - edited
  pull_request:
    types:
      - edited

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update dependencies
    # TODO(shakefu): Figure out what's supposed to happen here after @tagoro9
    # can explain wtf he was up to - remove the skip
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.OPEN_TURO_GITHUB_TOKEN }}
